ARG FLARE_BASE_IMAGE=flare-base:latest
FROM $FLARE_BASE_IMAGE AS builder
RUN go run build/build.go
RUN export VERSION=$(cat RELEASE_VERSION) && \
    export COMMIT=$(cat RELEASE_COMMIT) && \
    export BUILD_DATE=`date +%FT%T%z` && \
    echo "$BUILD_DATE / $COMMIT / $VERSION" && \
    GOARCH=amd64 go build -ldflags "-w -s -X 'github.com/soulteary/flare/internal/version.Version=$VERSION' -X 'github.com/soulteary/flare/internal/version.Commit=$COMMIT' -X 'github.com/soulteary/flare/internal/version.BuildDate=$BUILD_DATE'" -o flare main.go
RUN if command -v upx >/dev/null 2>&1; then upx -9 -o flare.minify flare && mv flare.minify flare; else echo "upx not found, skip compression"; fi


FROM alpine:3.19
COPY --from=builder /app/flare /bin/flare
ENV TZ=Asia/Shanghai
RUN apk add tzdata && \
    cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    rm -rf /var/cache/apk/*
WORKDIR /app
CMD ["flare"]
